highlighter: rouge
github: [Repository metadata]

baseurl: "http://www.blythegrace.com"

# Collection Pages
collections:
  team:
    output: true
    output_ext: .html
    permalink: /professionals/:path/

# Sass
sass:
  sass_dir: scss
  style: :compressed
  line_numbers: true